# Generated by Django 3.2.2 on 2021-05-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_filed', models.FloatField()),
                ('hight_field', models.FloatField()),
                ('low_field', models.FloatField()),
                ('close_field', models.FloatField()),
                ('adj_close_field', models.FloatField()),
                ('volume_field', models.FloatField()),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
