# Generated by Django 3.2.2 on 2021-05-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapmodel',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
