# Generated by Django 3.2.2 on 2021-05-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_alter_scrapmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapmodel',
            name='date',
            field=models.DateField(),
        ),
    ]
